// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunicipalidadAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MunicipalidadAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MunicipalidadAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoEn = new DateTime(2026, 9, 9, 1, 48, 36, 597, DateTimeKind.Utc).AddTicks(6255),
                            Email = "admin@panajachel.gob",
                            Nombre = "Lic. Ricardo Gómez",
                            PasswordHash = "$2a$11$oIBp8zwl54Wnbe8pi8L3feidSjaWTcEZ.g94B.d0PAGsE6gnOswLu",
                            Rol = "administrador"
                        },
                        new
                        {
                            Id = 2,
                            CreadoEn = new DateTime(2026, 9, 9, 1, 48, 36, 802, DateTimeKind.Utc).AddTicks(7453),
                            Email = "proveedor@ellago.com",
                            Empresa = "Suministros El Lago S.A.",
                            Nombre = "Suministros El Lago S.A.",
                            PasswordHash = "$2a$11$8UpKpoET8YIzzMYBQV8DUOXiXxZYZ9lN/BkZIX7XO6/P1wgqXXF8e",
                            Rol = "proveedor"
                        },
                        new
                        {
                            Id = 3,
                            CreadoEn = new DateTime(2026, 9, 9, 1, 48, 37, 12, DateTimeKind.Utc).AddTicks(4876),
                            Email = "proveedor2@gmail.com",
                            Empresa = "Materiales Pana",
                            Nombre = "Materiales Pana",
                            PasswordHash = "$2a$11$Pbnw4InS51gHu6Ul8cg4Ue1dkJIltynQFvpVAAmpAE98kKwujzbnS",
                            Rol = "proveedor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
